[semantic_release]
version_toml = ["packages/core-py/pyproject.toml:project.version"]
version_pattern = [
  "packages/core-ts/package.json:\"version\": \"{version}\"",
  "packages/relay-server/package.json:\"version\": \"{version}\""
]
tag_format = "v{version}"
commit_message = "chore(release): v{version}"
major_on_zero = false

[semantic_release.changelog]
changelog_file = "CHANGELOG.md"

[semantic_release.remote]
type = "github"
